Improved "find_substr" implementations
1st/interview pull request #1
Opened 2016-06-21 20:16 UTC by ykalchevskiy

Fixed index error
Provided more "pythonic" implementation

2016-09-21 21:41 UTC, ykalchevskiy commented
Hi, @1st!
Any chances that you will merge this pull request?

2016-10-24 12:13 UTC, ykalchevskiy commented
@1st, m? :)

2016-10-24 12:14 UTC, 1st commented
Hey. I'm sorry, didn't have time to review it earlier. Will do it today evening. Thanks for notifications!

2016-10-24 12:35 UTC, 1st requested changes

2016-10-24 12:35 UTC, 1st commented on algorithms.md
> +    for i in range(0, len(string) - len(substring) + 1):
It looks like if we have two strings of lenght zero - why do we need to add this extra one mumber to have an empty iteration over empty strings?

2016-10-24 12:35 UTC, 1st commented on algorithms.md
> +    return any(substr == string[i:i + len(substr)] for i in range(len(string) - len(substr) + 1))
The same here

2016-10-24 14:52 UTC, ykalchevskiy commented on algorithms.md
> +    for i in range(0, len(string) - len(substring) + 1):
Of course we can add an extra step like `if substr == '': return True`, but the current code also checks this. Without an iteration we can not reach `return True`.
This `+1` is checked by a case with two non-empty strings with same length: we really need one iteration to compare them.

BTW, there is a typo in the patch: I used `substring` but `substr` is right. I will update it soon.

2016-10-26 08:53 UTC, 1st commented
Hi @ykalchevskiy.

Did you test your solution on edge cases (empty string, no substring found, substr is equal to original srting)?

2016-10-26 09:14 UTC, ykalchevskiy commented
Hi @1st,
Sure. We can add tests somewhere.
```python
import pytest


def find_substr(string, substr):
    for i in range(0, len(string) - len(substr) + 1):
        for j in range(0, len(substr)):
            if substr[j] != string[i + j]:
                break
        else:
            return True
    return False


def find_substr_py(string, substr):
    return any(substr == string[i:i + len(substr)] for i in range(len(string) - len(substr) + 1))


T = True
F = False


@pytest.mark.parametrize('string substr result'.split(), [
('', '', T),
('', 'a', F),
('a', '', T),
('a', 'a', T),
('a', 'aa', F),
('aa', 'a', T),
('abc', 'abc', T),
('abcd', 'abc', T),
('ababc', 'abc', T),
('ababcd', 'abc', T),
('abcabc', 'abcd', F),
])
@pytest.mark.parametrize('func', [find_substr, find_substr_py])
def test_(string, substr, result, func):
    assert func(string, substr) is result
```

And output:
```bash
$ py.test -q test_.py
......................
22 passed in 0.02 seconds
```

2016-10-26 09:16 UTC, 1st commented
Good. Can you please create teo folders - first for samples, and second for tests. And place code and tests in appropriate folders - "code" and "tests". Thank you

2016-11-04 13:27 UTC, ykalchevskiy commented
Hi @1st,

I think it would be better just to add tests as doctests as in the latter example 'permute_string' and in [the Python examples](https://github.com/1st/interview/blob/master/python.md#write-test-for-function). Do you agree?

2016-11-04 13:53 UTC, 1st commented
Yes, please do it in docstring. Good idea.

2016-11-04 13:55 UTC, ykalchevskiy commented on algorithms.md
> +    return any(substr == string[i:i + len(substr)] for i in range(len(string) - len(substr) + 1))
Answered.

2016-11-04 13:56 UTC, ykalchevskiy commented
Done :)

2016-11-09 20:38 UTC, ykalchevskiy commented
Hi @1st,

What about merge? :)

2016-11-10 14:26 UTC, 1st commented
Still waiting for response on comments in code. At least I see unresolved two comments - add comment to a function and don't use `any` by described reason.

2016-11-10 21:41 UTC, ykalchevskiy commented
Oh, unfortunately I don't see any unanswered comments :( Where are they?

2016-11-11 09:32 UTC, 1st commented
Scroll above on 4 comments to see two unresolved coments. Comments to file in this trhread of discussion.

2016-11-11 09:51 UTC, ykalchevskiy commented
I see only these comments, but I have already answered.
<img width="706" alt="2016-11-11 12 48 06" src="https://cloud.githubusercontent.com/assets/1052035/20210957/8b98c890-a815-11e6-833d-22864a7ab78a.png">

2016-12-01 10:41 UTC, 1st commented
Hi Yan.

I see this comments unresolved:

<img width="749" alt="screen shot 2016-12-01 at 11 39 37 am" src="https://cloud.githubusercontent.com/assets/630224/20790935/f2be855a-b7ba-11e6-91ef-25bb51f1c287.png">

Also note that I have moved all chapters to the chapters/ directory. Sync before you will make final changes. Thank you.

2016-12-03 11:46 UTC, ykalchevskiy commented
Hi, @1st,

Unfortunately this review is **pending**: it means these comments are only visible to you!

https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/#reviewing-the-proposed-changes-in-line-comments

2016-12-03 11:56 UTC, ykalchevskiy commented
Anyway, about ```any```: actually it will iterate up to first element for which ```bool(el) is True```. It states in the docs: https://docs.python.org/2/library/functions.html?highlight=any#any
Also we can check it using something like this:
```python
def f(x):
  print x
  return x
any(f(i) for i in [1, 0]) 
```
Only ``1`` will be printed.

2016-12-03 12:47 UTC, ykalchevskiy commented
I just added a description and rebased changes to fit updated structure.

2017-01-04 21:39 UTC, ykalchevskiy commented
Hi @1st,

Let's finish it. What do you think?

2017-01-29 14:32 UTC, ykalchevskiy commented
Hi @1st,

Any comments? :)

2017-02-09 19:15 UTC, ykalchevskiy commented
Hi @1st,

One more time...

2017-02-09 19:20 UTC, merged

2017-02-09 19:21 UTC, 1st commented
Sorry for the long ignoring. It's a lot of work here. Congratulate you with the first push to this repository!